---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvcmovie
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mvcmovie
    spec:
      containers:
      - name: mvcmovie
        image: yadavn01/mvcmovie:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: pvc-mvcmovie
  selector:
    matchLabels:
      app: mvcmovie
---
apiVersion: v1
kind: Service
metadata:
  name: mvcmovie
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: mvcmovie
